### ISSUE TITLE
If multiple models are used in one program, what is the behavior of the program?

### ISSUE THREAD

**Issue by wangxianliang** [facebook/fb-caffe-exts#14]
The file "Predictor.h" contains the following statement:
        **folly::ThreadLocalPtr <caffe::Net<float>> predictors_;**
and it is a member of the class Predictor, if I have multiple Predictor instance, what will happen?

Say, I want to use both GoogLeNet and CaffeNet in one program, then combine the scores of these two models. Both of the models are called in multiple threads, what would happen?

eg:
  predictor_1 = folly::make_uniquecaffe::fb::Predictor(FLAGS_prototxt_path_1,
                                                        FLAGS_weights_path_1);
  predictor_2 = folly::make_uniquecaffe::fb::Predictor(FLAGS_prototxt_path_2,
                                                        FLAGS_weights_path_2);
and the thread function is as follows:
void thread_func()
{
    ...
    // When calling in a worker thread
  caffe::Blob<float> input_blob;
  input_blob.set_cpu_data(input_data); // avoid the copy.
  const auto& output_blobs_1 = predictor_1->forward({&input_blob});
 const auto& output_blobs_2 = predictor_2->forward({&input_blob});
...
}

What is the behavior of the above code?

Thanks a lot!

**Comment by ajtulloch** [comment]
These aren't `static`, they're just thread-local instances attached to the Predictor, so the semantics you'd expect (different models, different threads) will be exactly what happens.
