### ISSUE TITLE
Some questions about using Predictor

### ISSUE THREAD

**Issue by AIROBOTAI** [facebook/fb-caffe-exts#20]
Hi all,

I'm interested in using Predictor in Caffe. However I have following questions about its usage:
- Can it be used in training phase so as to reduce memory consumption? If not, is there a convenient way to do so?
- When using Predictor, should I replace all "Net" class with "Predictor" class in my code? Is there a more concrete example?

Thanks in advance!

**Comment by ajtulloch** [comment]
- Yes, the same idea can reduce memory consumption. It won't work out of the box, but it's possible.
- Instead of invoking caffe::Net(...), invoke caffe::fb::Predictor(..., optimization::...)
