### ISSUE TITLE
issues building torch2caffe

### ISSUE THREAD

**Issue by biggerlambda** [facebook/fb-caffe-exts#21]
How do i build torch2caffe ? I have installed all the dependencies . However the first few line of torch2caffe.lua says require "torch2caffe.lib" which was not there in the repo and there were no instructions to build.

**Comment by biggerlambda** [comment]
Bump! Can anyone point to instructions on how to build ?

**Comment by yuvalaviel** [comment]
you don't need to build anything in torch2caffe. simply follow the instruction.
Indeed there is no torch2caffe.lib in the repo. It works without this lib. I don't know lua so I don't understand why.

There is an issue, however, with PYTHONPATH ans LD_PRELOAD environment variables. see other issue for solutions.

HTH,
Yuval.
