### ISSUE TITLE
Usage of predictor

### ISSUE THREAD

**Issue by Timo-hab** [facebook/fb-caffe-exts#25]
Hi,

I want to optimize my model using predictor, but I am not sure how to use the provided code?
Is there any guidance or example how to use it? 
I need to drag and drop the files in src and include folders in caffe and then rebuild it, right? What are the next steps? 

Where can I include python bindings, that I can use it with python (pycaffe)? 
For example something like this:

```
...
net = predictor(caffe.Net('net_with_data_layer.prototxt', 'weights.caffemodel'))
net.forward() 
...
```

I am thankful for any hints!

**Comment by vishar0** [comment]
The Predictor class here doesn't have python bindings, this is meant to be used for C++ based prediction services build over caffe.
