### ISSUE TITLE
How to use predictor

### ISSUE THREAD

**Issue by akeem313** [facebook/fb-caffe-exts#34]
I had search all of the issues about usage of predictor,but not ideas of how to use it.
the things i had tried:
       i had install folly success in ubuntu14.04 with gcc-4.9.3 and boost-1.65.1. 
and then , push all *.h into [caffe_root]/include, *.cpp into [caffe_root]/src/caffe/,  
and then, set set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") into CMakeLists.txt, 
and then, set folly\double-conversion 's include directory and lib directory.
but last,when I building the caffe,I alse got error:"error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options" 
and error in folly like this:"include/folly/Portability.h:39:1: error: expected unqualified-id before 'using'  using integral_max = std::integral_constant<I, (A < B) ? B : A>;"
       could you show how to build caffe with predictor ?
thanks.

**Comment by akeem313** [comment]
i have use predictor and reduce memory success.  we can make out code like the *test.cpp.

**Comment by GeorgeBohw** [comment]
can you release a sample?
Thanks!

**Comment by FreshGitter** [comment]
in torch2caffe.lua 
what is torch2caffe.lib？where
Thanks!

**Comment by oscarriddle** [comment]
Can you update a detailed installation procedure?
That would be very helpful!
Thanks,

**Comment by allenling** [comment]
hi
@akeem313 

Is your gpu memory really be reduced?

**Comment by akeem313** [comment]
> hi
> @akeem313
> 
> Is your gpu memory really be reduced?

Yes, predictor would create share relationship in the first time running. so, the gpu mem would be reduced from second times.
